apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "events.fullname" . }}
  labels:
    {{- include "events.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "events.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "events.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: events
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.ports.container }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}