apiVersion: v1
kind: Service
metadata:
  name: {{ include "events.fullname" . }}
  labels:
    {{- include "events.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.ports.service }}
      targetPort: {{ .Values.ports.container }}
      protocol: TCP
      name: http
  selector:
    {{- include "events.selectorLabels" . | nindent 4 }}